### ISSUE TITLE
Unable to switch to rich edit mode

### ISSUE THREAD

**Issue by regs01** [nextcloud/notes-android#1754]
**Describe the bug**
Just can't switch to rich edit mode

**To Reproduce**
1. Click rich edit mode button
2. Error appears

**Expected behavior**
Switch to rich edit mode

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 4.0.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10
 - Device: Huawei P30

**Server**
 - Nextcloud version: 26.0.0
 - Nextcloud Notes version (server app): 4.7.2

**Screenshots**
![Screenshot_20230408_185029_it niedermann owncloud notes](https://user-images.githubusercontent.com/10468217/230731277-96e6dcba-14ec-41a5-9c0a-77991965c7ba.png)

**Comment by mstyp** [comment]
I am experiencing the exact same bug. The default nextcloud files app can load rich documents editer just fine.

**Comment by daffydock** [comment]
Same problem and have had it since day one. Server Notes app was a bit buggy as well but is fine after a number of updates since. Still can't use it on the mobile app. 

I also get the odd error "The document has been changed outside of the editor. The changes cannot be applied." When I open any one note. If I let it run for long enough. Sometimes it will give me the option to pick the saved version or the current version. 

The error you show on your screen still shows up superimposed over everything at the bottom. It is not really usable.

**Comment by regs01** [comment]
I tried Dev version. And it is working. However on first try i got conflict error to pick two different versions of note. Has not been there since then. Keep testing.

**Comment by daffydock** [comment]
> I tried Dev version.
> 
> This is one tried (artifact with zip file at the bottom) https://github.com/nextcloud/notes-android/actions/runs/5331495052
> 
> And it is working. However on first try i got conflict error to pick two different versions of note. Has not been there since then. Keep testing.

Tried Dev version suggested. Nothing has changed. Issues continue.

**Comment by regs01** [comment]
> Tried Dev version suggested. Nothing has changed. Issues continue.

1. What kind of issues?
2. You sure you running Dev version? It installs alongside the release version and has Dev in its icon.

**Comment by daffydock** [comment]
@regs01 

1. Same as the ones posted on my original post. 
2. Yes.

**Comment by regs01** [comment]
> 1. Same as the ones posted on my original post.

`Error while loading rich edit`?

**Comment by Uatschitchun** [comment]
I've got the same bug but only with one of my 2 servers!?
What infos are needed?

**Comment by daffydock** [comment]
> > 1. Same as the ones posted on my original post.
> 
> `Error while loading rich editing`?

Fair. 
To answer your question more specifically, I get both, the error you opened this ticket for, and also the error(s) I posted in my post after. Both still continue on different phones with different versions of Android, ranging from 7+ onward. 
Standard Notes app from F-Droid or Dev version. It makes no difference.

**Comment by daffydock** [comment]
> I've got the same bug but only with one of my 2 servers!? Seems to be a timeout issue?

Just to be clear, @Uatschitchun: When you say _2 servers_, do you mean two different instances on the same server, or two separate physical servers? I assume you mean two separate machines. As I have a production and a testing one instance, both on the same machine, one on 26+ and the other on 27 and I get the same issue in both. Maybe it could be a time out issue.

**Comment by Uatschitchun** [comment]
Yes, 2 instances hosted in different servers

**Comment by mahenkpatel** [comment]
Facing same issue on Nextcloud notes version 4.1.0 RC1. The nextcloud server is running on Nextcloud Hub 5 (27.0.0)

**Comment by JohnDSR** [comment]
Having same issue with Nextcloud Notes - Android version 4.1.0 RC1 from F-Droid.  Server is Nextcloud-AIO 27.0.2.

**Comment by pascalw** [comment]
I'm facing this issue as well. For me it only started after upgrading the server to 27. Before the upgrade I was running 24, so I'm not sure since which version exactly this issue started.

**Comment by psabc** [comment]
I fixed this error by enabling the Text app in my Nextcloud instance, it was disabled before. Maybe that helps some of you.

**Comment by regs01** [comment]
It's working in dev, but doesn't work in stable. Even after update to 4.1.0 final.

**Comment by daffydock** [comment]
> It's working in dev, but doesn't work in stable. Even after update to 4.1.0 final.

Just for those who would like to try, the Dev apk has expired. You cannot simply download it from the link, posted closer to the top.

**Comment by regs01** [comment]
> > It's working in dev, but doesn't work in stable. Even after update to 4.1.0 final.
> 
> Just for those who would like to try, the Dev apk has expired. You cannot simply download it from the link, posted closer to the top.

Find lastest with artefacts in Actions. Dev is working. Although loading 10 seconds and won't work without connection.

https://github.com/nextcloud/notes-android/actions

**Comment by daffydock** [comment]
@regs01 

Tried with latest Notes Dev, built 18 hours ago as of this writing. Error still pops up: "Error while loading rich editing..." Giving the option to switch to Plain. Agreed that Rich Text does come up after 10+ seconds or so, but that would sometimes happen before, sometimes. 

Error message still persists at the bottom, even with the Rich Text appearing, blocking the lower button at the bottom right and it won't disappear unless one does opt to switch back to plain. Strange since this has been going on for 8 months now.

**Comment by regs01** [comment]
Sure you are launching Notes Dev app, not the original one? It's a different app. And rich edit mode is only working online.

**Comment by daffydock** [comment]
> Sure you are launching Notes Dev app, not the original one? It's a different app. And rich edit mode is only working online.

Who would confuse the two? It literally loads with the word "Dev," as a splash screen and in a large a font. So, to answer your question: Yes, I am sure. Unfortunately, the error continues. 

Albeit I do not know if this is the same/or related error as OP's, I am now also getting this while using the alpha build on one of my phones. Maybe it will be beneficial as to further shed light into this issue:


----
----



App Version: 4.2.0 Alpha1
App Version Code: 40020000
App Flavor: dev

Files App Version Code: 30260090 (PROD)
Files App Version Code: 20231209 (DEV)

---

OS Version: 3.18.31-perf-gd33f902(1906418273f7d)
OS API Level: 24
Device: sf340n
Manufacturer: LGE
Model (and Product): LG-M470 (sf340n_global_ca)

---

java.lang.NullPointerException: Attempt to invoke interface method 'void com.nextcloud.android.sso.api.NextcloudAPI$ApiConnectedListener.onConnected()' on a null object reference
	at com.nextcloud.android.sso.api.AidlNetworkRequest$1.onServiceConnected(AidlNetworkRequest.java:79)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1535)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1563)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6317)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by bladem2003** [comment]
Where can I get the dev version?

**Comment by sandpaperback** [comment]
> I fixed this error by enabling the Text app in my Nextcloud instance, it was disabled before. Maybe that helps some of you.

This fixed the issue for me immediately. Thank you!

**Comment by daffydock** [comment]
@bladem2003 
> Where can I get the dev version?

You can find it under *actions*. It is  a bit of a moving target as new APKs are built constantly. This is the latest I saw today, as of this morning. 

https://github.com/nextcloud/notes-android/actions/runs/7404915333

**Comment by giogua** [comment]
I had a similar issue, except I could not edit my notes from my android phone at all. All the notes opened in preview mode and the switch to the edit mode did nothing at all.

For me disabling and re-enabling the text app (it was originally enabled for me) fixed the issue.

**Comment by repsorp** [comment]
Check this in parameters:
![Screenshot_20240714-002036.png](https://github.com/user-attachments/assets/7fc11f28-1333-4fdd-97cb-692358087613)

Make sure it's not enabled

**Comment by giogua** [comment]
It was enabled for me. Disabling that settings had no effect since the editing started working again after restarting the text app.

What that settings does and why disabling It should fix the issue?

**Comment by repsorp** [comment]
Here (Ubuntu 24.04, Notes 4.3.0) "Plain edit mode" floating button 
doesn't work when "Direct Edit" enabled.
https://github.com/nextcloud/notes-android/issues/2258

**Comment by giogua** [comment]
Thanks!

**Comment by mitexleo** [comment]
Still facing this issue (AIO, Hub 9)

**Comment by omiday** [comment]
> Still facing this issue (AIO, Hub 9)

Try with these settings:
- Direct Edit [X]
- Notes opening behavior:Plain preview: [X]

**Comment by regs01** [comment]
> Still facing this issue (AIO, Hub 9)

For me its working now. Not sure I've noticed at what point it started to work.

**Comment by omiday** [comment]
> > Still facing this issue (AIO, Hub 9)
> 
> Try with these settings:
> 
>     * Direct Edit [X]
> 
>     * Notes opening behavior:Plain preview: [X]

It turns out that I had to disable "Direct Edit" in order to be able to edit. Plain text editor provides the [context based editing](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#why-arent-there-any-buttons-to-apply-formatting) features.

**Comment by omiday** [comment]
> > Still facing this issue (AIO, Hub 9)
> 
> For me its working now. Not sure I've noticed at what point it started to work.

@regs01 What is your Android version?

**Comment by tomchiverton** [comment]
Brand new install from F-Droid, newly added app to Nextcloud itself, had exact same issue.

It's been two years and still not fixed ? Is this app dead then ?

**Comment by tomchiverton** [comment]
I have both Notes and Text apps enable in NextCloud.

Android 14 on Pixel 6a.

**Comment by tomchiverton** [comment]
This has randomly started to work today.

**Comment by regs01** [comment]
> This has randomly started to work today.

It was fixed, but it's an online web editor. So you need to be connected to open and work with it. Very inconvenient.

**Comment by elibroftw** [comment]
2 years???

**Comment by joshtrichards** [comment]
Likely a duplicate of #1935

**Comment by PaulWebb** [comment]
Samsung A35. Android 15. Latest version from Fdroid. Also tried latest version from Google play store. 4.12.0 on server. 
Same error as OP.

**Comment by regs01** [comment]
> Samsung A35. Android 15. Latest version from Fdroid. Also tried latest version from Google play store. 4.12.0 on server. Same error as OP.

Are you online?

**Comment by PaulWebb** [comment]
Yes

**Comment by charredchar** [comment]
> Likely a duplicate of [#1935](https://github.com/nextcloud/notes-android/issues/1935)

This seems possible but that user had the issue "resolve itself" so no real solution to anyone still facing the same problem.
One thing I will mention is I've had this error for awhile now and today I caught a glimpse of this same `java.lang.NullPointerException: item is null` error pop up.
I'm wondering if this is more of an issue on the server side than an issue on the Android app itself. As other comments previously have said it was fixed with stuff like "enable text app on your Nextcloud instance" but that's not the issues for others. Maybe also proxy settings? So if multiple things can cause the same issue in the Notes app we will need a better way to determine each cause instead of people just saying, "I have this issue too." Maybe some kind of logging in the app itself?

**Comment by berenddeschouwer** [comment]
Still happens on a Pixel 6a, Android 16, Notes App 4.3.1, Nextcloud Hub 31.0.6, Notes 4.12.1.

The last http request is:
```
GET /nextcloud/index.php/apps/notes/api/v1/settings HTTP/1.1
```
(*note:* this is after the https proxy)

Response:
```
{"notesPath":"Notes","fileSuffix":".md","noteMode":"rich"}
```

App log:
```
App Version: 4.3.1
App Version Code: 40030192
App Flavor: play

Files App Version Code: 30310490 (PROD)

---

OS Version: 6.1.124-android14-11-g8d713f9e8e7b-ab13202960(13578606)
OS API Level: 36
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

java.lang.NullPointerException: item is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.Single.just(Single.java:839)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.changeToEditMode(NoteDirectEditFragment.kt:335)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.handleLoadError$lambda$10(NoteDirectEditFragment.kt:204)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.$r8$lambda$qIpAlct9ayneQIzQFWgMgsA_Idc(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment$$ExternalSyntheticLambda5.onClick(D8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:357)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8083)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:8060)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31549)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9067)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)

```

**Comment by berenddeschouwer** [comment]
The closest to HTTP errors I can find, is that when switching between plain and rich text, the server ships 409 (simultaneous edit) twice.  That's an empty http, so it might set the note to null.

**Comment by Eklinaar** [comment]
I am also getting the same error exactly as the original post described on a Moto G Power.  Using NextCloud Notes 4.4.  Every time I try to open Rich Editing, I get the error "Error while loading rich editing"

**Comment by theshatterstone** [comment]
Can confirm I'm also getting this with Nextcloud Notes 4.4.2 Android 15. Every time I try to open Rich Editing, I'm met with the same error. Everything else seems to work fine, including notes sync, and reading and writing notes using the plain text editor

**Comment by marmolak** [comment]
Hi. I have same issue (unable to switch to rich text mode) with Xiaomi phone with Android 14, Nextcloud 31.

**Comment by YoannPa** [comment]
This issue appeared very recently on my Phone, after using Nextcloud Notes smoothly for several months.
The error is also associated with a sync error message.
Consequently, I cannot use the app anymore.

Smartphone:

- Nextcloud Notes-Version (android app): **4.5.0**
- F-Droid or Play Store: happens with both.
- Android-Version: **13**
- Device: Fairphone 4

Server:

- Nextcloud version: **Nextcloud Hub 9 (30.0.13)**
- Nextcloud Notes version (server app): **4.12.2**

This issue has been going one since about 2 years and half. I think it would be nice to address it.

**Comment by popy2k14** [comment]
I had the same issue and solved it temporarily by deleting the app data. Then rich edit is working when I am online. 

If I switch my networks off and rich edit doesn't work. 

So it seems it just works offline?
